<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonKeranjang</name>
   <tag></tag>
   <elementGuidId>198ec41c-e247-43b1-8460-2692d2716dc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-lg.btn-addtocart.addtocart-js.btn-choosevariant-js</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product_form_8016902750451']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b58ef44-94f8-4561-945f-18272ec7d634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>addtocart</value>
      <webElementGuid>0c6f7178-bec1-4f96-b7bb-77d72b0dbee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-addtocart addtocart-js btn-choosevariant-js</value>
      <webElementGuid>fc0361a1-0f73-472d-bedd-b3ddc8744ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Keranjang</value>
      <webElementGuid>426f7e14-a808-4a89-a08a-39d177637089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_form_8016902750451&quot;)/div[@class=&quot;tt-row-custom-01 addtocart-container&quot;]/div[@class=&quot;col-item&quot;]/button[@class=&quot;btn btn-lg btn-addtocart addtocart-js btn-choosevariant-js&quot;]</value>
      <webElementGuid>8a42a4cf-d7bd-4d0e-9fae-4666afc141a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_form_8016902750451']/div/div[2]/button</value>
      <webElementGuid>24d769de-029a-466f-9649-4e463b4e6913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 75.000'])[1]/following::button[1]</value>
      <webElementGuid>915c43d8-5ae8-4529-bc60-590e37004567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cicil 12x'])[1]/following::button[1]</value>
      <webElementGuid>b89f1348-6a03-48c2-9ca4-ef86957c7943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Designers:'])[1]/preceding::button[1]</value>
      <webElementGuid>9ce62b41-b6f4-45a1-834e-1ae441dc66a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/button</value>
      <webElementGuid>54499111-fdfc-4ad4-977c-2dc893994c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '+ Keranjang' or . = '+ Keranjang')]</value>
      <webElementGuid>38051d3a-f647-47ff-aeb9-232e7092e76b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
