<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pickSizeOfProduct</name>
   <tag></tag>
   <elementGuidId>5af58059-ea86-40e1-8797-f179894ccf8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.tt-options-swatch.options-large > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-pages-banners']/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6bafdcae-b85a-4a9c-abca-0b9faf94b1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>03f4b836-960d-467d-8a28-588e3ab73276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>8a93cfe2-686b-4a46-ad59-0e0a2636416e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>e8f11783-8491-4903-a0db-0513e42c5a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-product-template&quot;)/div[@class=&quot;container-indent&quot;]/div[@class=&quot;container container-fluid-mobile&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;tt-product-single-info stickprcolheight-js&quot;]/div[@id=&quot;product-pages-banners&quot;]/div[@class=&quot;tt-swatches-wrapper&quot;]/div[@class=&quot;tt-swatches-container tt-swatches-container-js&quot;]/div[@class=&quot;tt-wrapper&quot;]/ul[@class=&quot;tt-options-swatch options-large&quot;]/li[2]/a[1]</value>
      <webElementGuid>e8852e15-305f-462f-aba3-a05beb927281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-pages-banners']/div/div/div/ul/li[2]/a</value>
      <webElementGuid>b6aa33e6-b513-4536-bc03-d18468781cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'M')])[62]</value>
      <webElementGuid>b6577545-a398-4bb1-823b-18a72574f620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Size:'])[1]/following::a[2]</value>
      <webElementGuid>7d82c44f-dbf6-402c-9f24-ed7201c1aed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR 900.000'])[1]/following::a[2]</value>
      <webElementGuid>79d75c00-99aa-4224-a52a-aacc16f3990a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih size untuk menambahkan produk ke keranjang.'])[1]/preceding::a[3]</value>
      <webElementGuid>c43209e0-8b3b-4556-92c2-3d5e7ea024bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='M']/parent::*</value>
      <webElementGuid>b22de94a-0d02-43ba-9acc-bc055db8e904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[27]</value>
      <webElementGuid>ccaaaf8c-e0dc-4f16-bd8c-9288aba9496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>ab1d9c93-9faa-40d7-aaec-588634172638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>d3168def-4674-4e00-bdb3-7c8de3a936bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
