<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonIconToLogin</name>
   <tag></tag>
   <elementGuidId>8adf8e1d-19f3-4ddf-9e9c-3081e922296d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tt-account.tt-dropdown-obj > button.tt-dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-action']/div[3]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>664d5a71-d444-4118-ba51-a895519ee6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tt-dropdown-toggle</value>
      <webElementGuid>f61b7fae-0ac9-44ec-b0fd-b8bab3291a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-action&quot;)/div[@class=&quot;tt-desctop-parent-account tt-parent-box js-on-hover tt-parent-box-padding cls&quot;]/div[@class=&quot;tt-account tt-dropdown-obj&quot;]/button[@class=&quot;tt-dropdown-toggle&quot;]</value>
      <webElementGuid>c9960b15-e4a3-4562-a6a5-81691d385117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-action']/div[3]/div/button</value>
      <webElementGuid>70e45ec8-3fc2-4e0e-963c-c75fa9bee796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qty'])[1]/following::button[1]</value>
      <webElementGuid>5c2e0bdb-27da-473c-9210-68bf436c8dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[2]/preceding::button[1]</value>
      <webElementGuid>721ce6e7-a0b3-46b4-ba06-c928f7665639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[2]</value>
      <webElementGuid>85a7b2e1-becf-40c8-949b-425e3453d500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>e49adb76-8296-4195-b56e-c98aa2349ead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
