<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>displayPopUp</name>
   <tag></tag>
   <elementGuidId>e91389f7-9dbb-49a8-8f8b-ba772ab6590e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#automizely_marketing_popup_bars</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='automizely_marketing_popup_bars']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>de35a128-69fb-48a7-b8c0-b39e74bff858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e35f6050-42ad-4665-92bd-958f117f9a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>619088d1-ad9b-4f19-a469-19a7fa5614ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Automizely Marketing popup bars</value>
      <webElementGuid>069881bc-3792-4451-9786-8eeacc1bef66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/apps/automizely-messages/layers/popup-bars/?visitCount=1</value>
      <webElementGuid>d0200d20-4e38-4573-a813-6b44480e1138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>automizely_marketing_popup_bars</value>
      <webElementGuid>ce4b316b-fb75-4f7a-9b2a-8185c8df2a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;automizely_marketing_popup_bars&quot;)</value>
      <webElementGuid>d580fe16-1850-4a19-9ff6-ded151241ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='automizely_marketing_popup_bars']</value>
      <webElementGuid>d54a1b35-badc-4c22-9efc-a73df3647a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='conversions_layers_root']/iframe</value>
      <webElementGuid>d60d021d-c4d8-435d-be3d-0b54cefa14e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/iframe</value>
      <webElementGuid>d7bf3c50-7162-4094-a31f-96fc215a829a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Automizely Marketing popup bars' and @src = '/apps/automizely-messages/layers/popup-bars/?visitCount=1' and @id = 'automizely_marketing_popup_bars']</value>
      <webElementGuid>4f8c9b2a-3541-498c-911a-538e0f6d1050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
