<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxInfoBySMS</name>
   <tag></tag>
   <elementGuidId>9d3a77f8-f338-445c-b326-cd39547703dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sms_marketing_opt_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sms_marketing_opt_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdd3f099-b743-4aa3-969d-dab25fe8e513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b9b18b14-8787-469e-9493-c6ae1158cc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sms_marketing_opt_in</value>
      <webElementGuid>25a1f6d8-b136-4e9e-b49f-84c4326f9ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sms_marketing_opt_in</value>
      <webElementGuid>41442a14-ffaa-4f2d-9929-c13395d3e5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d9a3b0a2-10dc-4a5c-8191-fe23279e7d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acceptSmsMarketingCollapsible</value>
      <webElementGuid>7d2f02b5-a867-4ec8-b64f-72f118a1bc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1mmswk97 _1fragemhi _1fragemhg _1fragemhk _1fragemhe _1fragemic _1fragemi9 _1fragemif _1fragemi6 _1fragem4g _1fragem3w _1fragem50 _1fragem3c _1fragemf3 _1fragemf5 _1fragemh4 _1fragem1w _1fragemlk _1fragemle _1fragemlq _1fragemev _1fragemm1</value>
      <webElementGuid>04f96c2e-e9f3-41cc-b4d3-968aa5ecb003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sms_marketing_opt_in&quot;)</value>
      <webElementGuid>89795102-3ab9-447c-9e51-6acd21fa7645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sms_marketing_opt_in']</value>
      <webElementGuid>b9f30870-c178-4ad5-8f87-63f600bf6bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div/div/div[2]/div/div/section/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>9f8e4c39-debe-4903-a87a-f16da22bfece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>e12fcd62-95af-47c8-920b-9fb9648a7fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sms_marketing_opt_in' and @name = 'sms_marketing_opt_in']</value>
      <webElementGuid>f8fba63b-5734-4525-a9aa-3b2c80c321d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
