<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxClothingCategory</name>
   <tag></tag>
   <elementGuidId>2d838492-ca43-48da-bbe0-09837ca126da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boost-pfs-filter-tree-pf-t-category > div.boost-pfs-filter-option-content-inner > ul.boost-pfs-filter-option-item-list.boost-pfs-filter-option-item-list-multiple-list > li.boost-pfs-filter-option-item.boost-pfs-filter-option-label > button.boost-pfs-filter-button > span.boost-pfs-check-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='boost-pfs-filter-tree-pf-t-category']/div/ul/li/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06840686-fd22-4184-8b62-e7e7868ce410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boost-pfs-check-box</value>
      <webElementGuid>c363fe6e-8a13-40dd-8890-d3fdf1f95535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b4ed5cc0-2a51-43e9-9074-d57746c11a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>41a19b6e-f76d-4773-9722-d8ecabe173f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>Clothing</value>
      <webElementGuid>be32a593-9c31-4fc0-9ed5-e59bf035af36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boost-pfs-filter-tree-pf-t-category&quot;)/div[@class=&quot;boost-pfs-filter-option-content-inner&quot;]/ul[@class=&quot;boost-pfs-filter-option-item-list boost-pfs-filter-option-item-list-multiple-list&quot;]/li[@class=&quot;boost-pfs-filter-option-item boost-pfs-filter-option-label&quot;]/button[@class=&quot;boost-pfs-filter-button&quot;]/span[@class=&quot;boost-pfs-check-box&quot;]</value>
      <webElementGuid>91c66d7e-7179-496e-837a-5cec0529d515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='boost-pfs-filter-tree-pf-t-category']/div/ul/li/button/span</value>
      <webElementGuid>5a985674-3198-4f25-a4cd-02308ad0a580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li/button/span</value>
      <webElementGuid>a445a1c9-4e90-4911-9ab9-470d46ad7b0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
