<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldFirstName</name>
   <tag></tag>
   <elementGuidId>097a08ea-166b-467f-9edd-dfa697245248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f8d6c9f-369d-4c24-ae83-78375be57b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField1</value>
      <webElementGuid>d9e73e98-f2d7-4bc9-9871-58f85150cdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>74672318-1284-4cd6-926e-154816303363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama depan (opsional)</value>
      <webElementGuid>881814ec-fb4f-409d-8ba9-a3ab80eff04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74e4156c-2368-4e47-9a9f-f5ee5a6b66e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>57d98865-e547-4157-86e9-f3213d1673eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField1-label</value>
      <webElementGuid>8a2f7e84-33ff-4662-903c-6bf5a3e0039b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping given-name</value>
      <webElementGuid>c14d7694-135c-4832-a799-ca8c8dce46df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-protected-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>835445a5-af97-46c9-9f4e-ccede075274a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemlv _1fragemh4 _1frageml5 _7ozb2ur _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>4cfac719-faba-40b3-a2e0-0166d114ed38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField1&quot;)</value>
      <webElementGuid>c13627bb-541a-48b3-8648-a9eaebd6f32c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField1']</value>
      <webElementGuid>9d5efebd-6909-42d0-ad68-986152f803fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>3d4ef48f-7c6c-4f49-bfb7-2542f4469eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>14c64036-53b8-4ae2-a865-b36e775bb4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField1' and @name = 'firstName' and @placeholder = 'Nama depan (opsional)' and @type = 'text']</value>
      <webElementGuid>f1382861-a600-4e47-bd3a-175db7a27f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
