<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldPhone</name>
   <tag></tag>
   <elementGuidId>a81d2b13-9a91-40e0-88ca-c21ef1552ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5be166bc-8974-47e4-8d3c-b255ae2f8815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField7</value>
      <webElementGuid>26ad1dcb-c4a1-4220-b6fb-6577b3a021b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>e12b28e4-4900-4afc-af51-6d799b8f2234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Handphone</value>
      <webElementGuid>d2bebdfa-d505-4a17-8591-9a16f71c9782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>29b67a0e-500b-454d-a47c-8449ef738acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd30a430-0c36-41e0-b4be-14491c6c1f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField7-label</value>
      <webElementGuid>4b27ade1-eace-4506-b9f7-1bcecb391758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping tel</value>
      <webElementGuid>7d3b92be-9f92-47a9-a88c-fa4766dbd5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-protected-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2c450a8-12d8-4104-a225-482e76f788ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemlv _1fragemh4 _1frageml5 _7ozb2ur _1fragemhq _1fragemi0 _7ozb2u10 _7ozb2u1j</value>
      <webElementGuid>c45da004-f3fa-468a-b7b0-fe1bf5c523f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField7&quot;)</value>
      <webElementGuid>3f3e11b6-92b4-47f4-844c-6ce108cc6eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField7']</value>
      <webElementGuid>18c6b1b1-2e87-4b30-8589-7f799d29f483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[7]/div/div/div/input</value>
      <webElementGuid>ba709f86-86db-4e99-b00b-378e6aa70d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>fbf65544-8f8c-4e71-b35b-9c419625f593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField7' and @name = 'phone' and @placeholder = 'No Handphone' and @type = 'tel']</value>
      <webElementGuid>11f77602-ca4b-421d-b11d-f2228c0878a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
