<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldPostalCode</name>
   <tag></tag>
   <elementGuidId>010fe353-5278-4850-83bb-3664aa77c093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>695e12b3-2066-4a67-8e49-3ef31a7a821c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField6</value>
      <webElementGuid>1302a861-1bef-49d4-8f3f-5ced57412810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>fbfa007e-5667-4d64-a7bd-71431a815ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kode pos</value>
      <webElementGuid>32af2c69-b60c-4338-b215-c8e53ab1f6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee1601ad-025a-4394-a6d5-7f73ff90c8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d21b91ef-b3d8-4b51-90cb-c6d9be31c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad6da670-1ce4-4604-a2a9-1e175e5186ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField6-label</value>
      <webElementGuid>3e533679-cbd4-4c85-919b-95500bf6b283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping postal-code</value>
      <webElementGuid>a99b70b1-6c4a-4757-bc2c-af31c90748e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>characters</value>
      <webElementGuid>0ee73de0-292c-4daf-a017-030bf3e17d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemlv _1fragemh4 _1frageml5 _7ozb2ur _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>e504410c-958e-471f-84af-cf448f4c5e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField6&quot;)</value>
      <webElementGuid>5792ea50-395c-4741-b6e8-b443152dd531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField6']</value>
      <webElementGuid>10510635-a075-4116-a8d6-33f9ba63e9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[6]/div[2]/div/div/div/input</value>
      <webElementGuid>c9ed63f2-bbd4-405b-b775-bb1d672a66aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/input</value>
      <webElementGuid>4896247d-5cb1-4278-b364-0db81b69bea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField6' and @name = 'postalCode' and @placeholder = 'Kode pos' and @type = 'text']</value>
      <webElementGuid>e7464e04-63e9-4a34-95c1-566e86dcb897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
