<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldPickProvince</name>
   <tag></tag>
   <elementGuidId>bef4c286-d48d-44aa-b7ca-74c693eb6e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Select1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Select1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>49df0b63-0114-45c6-ad07-8346b9dbea8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone</value>
      <webElementGuid>6645f6ad-08c6-4b24-ba76-dfd3f7fd7281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select1</value>
      <webElementGuid>c7c8e647-5a05-4fd0-8717-2226f8fe3b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level1</value>
      <webElementGuid>5807d80f-9d8f-4d74-a252-12f6cef85538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_b6uH _1fragemm1 yA4Q8 vYo81 RGaKd</value>
      <webElementGuid>a14347d4-c1b4-4795-b7bf-828e8cc55afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta</value>
      <webElementGuid>d9200c36-3212-4ab9-ac3a-c51545399cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select1&quot;)</value>
      <webElementGuid>d4e5d2ae-fc59-44ce-a64a-6d9478f89139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Select1']</value>
      <webElementGuid>20193c97-a94a-4054-b0bb-0a71aa4fb2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[6]/div/div/div/select</value>
      <webElementGuid>f420bd4a-098e-48ca-86db-64eafa11de6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::select[1]</value>
      <webElementGuid>b530d7ee-812a-4478-9b90-7076f7bb8512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota dan kecamatan'])[1]/following::select[1]</value>
      <webElementGuid>a4f258f0-83f3-47dd-9a02-cc071745b08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode pos'])[1]/preceding::select[1]</value>
      <webElementGuid>d13628e4-5290-4361-b9e0-252d0c5400a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone'])[1]/preceding::select[1]</value>
      <webElementGuid>6048c996-ce50-4042-8a2f-12851c9edc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>591223e7-ea25-42f5-adbc-016332d50a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone' and @id = 'Select1' and (text() = ' AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta' or . = ' AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta')]</value>
      <webElementGuid>e1716967-c455-471a-840a-a3a9835cf4d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
