<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputLastName</name>
   <tag></tag>
   <elementGuidId>5fd4a6c5-2caa-4477-bfd0-537b636f3fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>710ffe65-a7da-4a20-8ff8-54a5bb7a1b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField2</value>
      <webElementGuid>fb1aede4-ab68-44ab-9d6b-85108d22f2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>bcba348f-f83a-4d39-af89-0cb8fc48a3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama belakang</value>
      <webElementGuid>3ccc3557-2039-44f5-bf1a-fa80802aabdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b07cef2e-32b6-4424-8609-87671501bb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18a3518d-b283-402c-8dca-6bc986cc55c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField2-label</value>
      <webElementGuid>863f4951-d90a-432c-8917-8d5e5db1eca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping family-name</value>
      <webElementGuid>896f52d0-7684-48d5-848c-b4c627a01926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-protected-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b806dd5f-47df-4a02-a716-c395a4781c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemlv _1fragemh4 _1frageml5 _7ozb2ur _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>e04570ef-3ec4-4fe2-b8c3-639d0116d41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField2&quot;)</value>
      <webElementGuid>e18c4120-1a8e-4e1a-b1bd-c3c68d6617c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField2']</value>
      <webElementGuid>74f490fe-5f7c-49c1-b9da-83493f9367a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>46e431c7-79ad-42e0-97cf-d0c8478257c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>4a97f9be-5f0d-46be-a95e-d9140452033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField2' and @name = 'lastName' and @placeholder = 'Nama belakang' and @type = 'text']</value>
      <webElementGuid>b6fbfb54-6a86-4a10-ba50-ab0b08560043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
