<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxInfoBySMS</name>
   <tag></tag>
   <elementGuidId>87f2c119-848a-430a-94bd-2db742b3dcb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sms_marketing_opt_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sms_marketing_opt_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70fd8e8a-e468-4e2a-b211-0c1e426eebf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f9ac4100-1177-4bb3-9d9c-b9baa419eaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sms_marketing_opt_in</value>
      <webElementGuid>228b5045-8665-4dd5-82fd-f2eb98df078e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sms_marketing_opt_in</value>
      <webElementGuid>b0b82104-2a93-47f7-a80d-79f4791139d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e92fad6-87c0-44d0-b5a9-1e65824a6c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acceptSmsMarketingCollapsible</value>
      <webElementGuid>b008d557-7601-4189-9513-1079453cba7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1mmswk97 _1fragemhi _1fragemhg _1fragemhk _1fragemhe _1fragemic _1fragemi9 _1fragemif _1fragemi6 _1fragem4g _1fragem3w _1fragem50 _1fragem3c _1fragemf3 _1fragemf5 _1fragemh4 _1fragem1w _1fragemlk _1fragemle _1fragemlq _1fragemev _1fragemm1</value>
      <webElementGuid>a6396c5e-242d-432b-b84e-c78fd89dc2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sms_marketing_opt_in&quot;)</value>
      <webElementGuid>2867819b-b798-4e4f-ad6e-0740682d3c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sms_marketing_opt_in']</value>
      <webElementGuid>6a41752a-5410-46cf-81bd-c9eea8232626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div/div/div[2]/div/div/section/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>c6ec21ef-3e3b-4c5b-8821-919b909f4904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>efc1e34c-839e-4527-a2b1-73f941799719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'sms_marketing_opt_in' and @name = 'sms_marketing_opt_in']</value>
      <webElementGuid>0e8f0412-7b4a-444c-90c3-bf46fc8864b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
