<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldFirstName</name>
   <tag></tag>
   <elementGuidId>bb0d3e45-2ee6-444e-a42f-9a061ed030fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ffb3f54-9fd4-461b-9b3f-d7003b8579bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField1</value>
      <webElementGuid>3ed384a8-b0b4-469e-80d3-4c6d845379e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>90361348-203b-4afc-b075-3597a27fcc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama depan (opsional)</value>
      <webElementGuid>d569dbe6-996c-42a1-83ff-2cf88ad0cb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4d86705-3e47-456e-8aad-fd1d78d09f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f880c35-643c-4c07-88b0-44606d09ed79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField1-label</value>
      <webElementGuid>75bfffe6-efd9-4aff-ae1b-c2428922c9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping given-name</value>
      <webElementGuid>7235626b-ded9-4f63-aa8e-43a1bc5d47a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-protected-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e05e02f8-6166-4089-80f0-262abb7f6f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemlv _1fragemh4 _1frageml5 _7ozb2ur _7ozb2u11 _7ozb2u1j</value>
      <webElementGuid>9eb05e66-556a-4bef-b0ce-faa087d605ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField1&quot;)</value>
      <webElementGuid>55fc8a59-a3be-43c3-808a-7d024b0aaddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField1']</value>
      <webElementGuid>20037dc0-1598-45bb-9dde-58f59f3037a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b7912501-c013-482c-a1f3-55f3d4b70688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>096163b9-87ce-4f95-8fe7-22e682bb6a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField1' and @name = 'firstName' and @placeholder = 'Nama depan (opsional)' and @type = 'text']</value>
      <webElementGuid>760bc237-df84-4fc9-b9a5-1ce2af1bbbaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
