<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldPickProvince</name>
   <tag></tag>
   <elementGuidId>c9bf01ef-0989-4ece-8544-2ef1ced1fe7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'zone' and @id = 'Select1' and (text() = ' AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta' or . = ' AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Select1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Select1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0eb1009e-5efa-4029-a7cc-e959ff59dab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone</value>
      <webElementGuid>a68e3173-7bc3-40e1-b3a7-6182d7f34d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Select1</value>
      <webElementGuid>fda1b896-596e-4ff4-b75a-d7f3db403f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping address-level1</value>
      <webElementGuid>1e23caa7-d355-434f-9784-9d4c4dfe3b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_b6uH _1fragemm1 yA4Q8 vYo81 RGaKd</value>
      <webElementGuid>641c1db4-7f85-40b7-ad7d-83c5dc0eafc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta</value>
      <webElementGuid>bcc25c6b-ebda-4aa6-9230-531d752d7dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Select1&quot;)</value>
      <webElementGuid>601d065d-a886-4874-b20a-6514520e8656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Select1']</value>
      <webElementGuid>0e4b15e6-f09f-41ca-9313-e3ce71105c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[6]/div/div/div/select</value>
      <webElementGuid>2f6f232b-d465-44d7-8297-9e1bf8985676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::select[1]</value>
      <webElementGuid>2b9a5e04-297d-430f-86ea-b86fa923ab5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota dan kecamatan'])[1]/following::select[1]</value>
      <webElementGuid>e0aa8d40-3f25-4482-bb32-dc33e0443abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode pos'])[1]/preceding::select[1]</value>
      <webElementGuid>ff9935a8-d257-4e09-a132-1134df3d07a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone'])[1]/preceding::select[1]</value>
      <webElementGuid>feb682b9-9ea2-4cc0-b3ca-f5dc61466f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>520ed351-309a-42f7-ac95-0bc43d43404b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone' and @id = 'Select1' and (text() = ' AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta' or . = ' AcehBaliKepulauan Bangka BelitungBantenBengkuluGorontaloDaerah Khusus Ibukota JakartaJambiJawa BaratJawa TengahJawa TimurKalimantan BaratKalimantan SelatanKalimantan TengahKalimantan TimurKalimantan UtaraKepulauan RiauLampungMalukuMaluku UtaraSumatera UtaraNusa Tenggara BaratNusa Tenggara TimurPapuaPapua BaratRiauSumatera SelatanSulawesi BaratSulawesi SelatanSulawesi TengahSulawesi TenggaraSulawesi UtaraSumatera BaratYogyakarta')]</value>
      <webElementGuid>e94148f6-cd43-44e5-80d3-e174a4575952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
