<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldPhone</name>
   <tag></tag>
   <elementGuidId>c5033416-bf34-4e5d-ad1e-dd0393f09032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextField7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextField7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a9bf138-5bf6-44c1-a704-58bf4e233a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextField7</value>
      <webElementGuid>0ba3cf12-2d80-4297-b184-a1258dc6a202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>a5e0c68e-12f4-427b-8560-1a2d35916912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Handphone</value>
      <webElementGuid>c47f0913-47e3-4dda-ab3e-1ed1839798b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4ca05440-3a35-4a8a-9b31-e238cc78a372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef31ca13-f905-4fbc-9341-91ffc0149a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextField7-label</value>
      <webElementGuid>ac3cb8f3-966a-40ea-8505-64048a06571a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>shipping tel</value>
      <webElementGuid>e06dd67a-9089-4fc9-aef0-0290b69bc023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-protected-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ae841fc-4737-4b08-8ae6-6d2030a71157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _1frageme0 _1fragemlv _1fragemh4 _1frageml5 _7ozb2ur _1fragemhq _1fragemi0 _7ozb2u10 _7ozb2u1j</value>
      <webElementGuid>a9575bb1-a54e-40bc-836c-d3f0eddcad67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextField7&quot;)</value>
      <webElementGuid>b7c707cd-c69b-403f-8b2f-787b47d84243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextField7']</value>
      <webElementGuid>c09e1615-c8ed-4a87-8017-33e770a91443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingAddressForm']/div/div/div[7]/div/div/div/input</value>
      <webElementGuid>af68381b-beef-4674-877c-3e3f7d1ff123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>9102a4c3-70fa-439d-a3b9-046649289aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextField7' and @name = 'phone' and @placeholder = 'No Handphone' and @type = 'tel']</value>
      <webElementGuid>929c2513-7f2e-42f8-b6f3-f7eb1238d84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
